import { MainLayout } from '@/components';
import PublicLayout from '@/components/Layout/PublicLayout';
import Providers from '@/contexts/Providers';
import PublicProviders from '@/contexts/PublicProviders';
import '@/theme/globals.css';
import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import { authOptions } from './api/auth';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: React.FC<Props> = async ({ children }) => {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <Head>
        <link rel="prefetch" href="/images/bg.webp" />
      </Head>
      <body className={inter.className}>
        {session && (
          <Providers>
            <MainLayout>{children}</MainLayout>
          </Providers>
        )}
        {!session && (
          <PublicProviders>
            <PublicLayout>{children}</PublicLayout>
          </PublicProviders>
        )}
      </body>
    </html>
  );
};

export default RootLayout;
