import Providers from '@/contexts/Providers';
import '@/theme/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: React.FC<Props> = ({ children }) => {
  return (
    <html lang="en">
      <Head>
        <link rel="prefetch" href="/images/bg.webp" />
      </Head>
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
};

export default RootLayout;
